# -*- coding: utf-8 -*-
"""DMDW_EXP10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnTVSNV2yJqmjpGrT3pqvuUQM7InmLTZ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Read the dataset
data = pd.read_csv('/content/iris.csv')  # Replace 'your_dataset.csv' with the actual path to your CSV file

# Extract features for clustering
features = data[['sepal_length', 'sepal_width']]

# Specify the number of clusters (change as needed)
k = 3

# Apply K-means clustering
kmeans = KMeans(n_clusters=k, random_state=42)
data['cluster'] = kmeans.fit_predict(features)

# Visualize the clusters
plt.figure(figsize=(10, 6))

# Define colors for each cluster
colors = ['blue', 'green', 'purple' ]

for cluster in range(k):
    cluster_data = data[data['cluster'] == cluster]
    plt.scatter(cluster_data['sepal_length'], cluster_data['sepal_width'], label=f'Cluster {cluster + 1}', color=colors[cluster])

plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], marker='X', s=200, color='red', label='Centroids')
plt.title('K-means Clustering')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.legend()
plt.show()